name: Go

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    env:
      GO_VERSION: 1.22.4
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Release
        run: make release
